### ISSUE TITLE
Crashes when trying to dump coin gift "bundle"

### ISSUE THREAD

**Issue by antigravities** [GMMan/GroupeesDownload#4]
Hi cyanic,

I'm getting the following error when trying to use this on my own account:

```
> GroupeesDownload dump-bundles --user-id XXXXXX --csrf-token "XXXXXXXX" --cookie "XXXXXXXX"
Getting page 1
...
Getting bundle 219/272: Sloth Apology Bundle
Something went wrong: System.ArgumentNullException: Value cannot be null. (Parameter 's')
   at System.Int32.Parse(String s)
   at GroupeesDownload.Scraper.ParseProducts(String html) in C:\Users\Alexandra\source\repos\GroupeesDownload\GroupeesDownload\Scraper.cs:line 288
   at GroupeesDownload.Scraper.GetBundleProducts(Int32 orderId) in C:\Users\Alexandra\source\repos\GroupeesDownload\GroupeesDownload\Scraper.cs:line 65
   at GroupeesDownload.Scraper.GetAllBundles() in C:\Users\Alexandra\source\repos\GroupeesDownload\GroupeesDownload\Scraper.cs:line 48
   at GroupeesDownload.Program.<>c.<<Main>b__3_2>d.MoveNext() in C:\Users\Alexandra\source\repos\GroupeesDownload\GroupeesDownload\Program.cs:line 121
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

The response from the XHR to /orders/ looks like this:

```js
(function(){

var actions = $('.profile-item[data-id=2135726] header > .actions.actions-not-revealed');
var actions2 = $('.profile-item[data-id=2135726] header > .actions.actions-revealed');
actions.removeClass('available');
actions2.removeClass('available');

if (ProfileApp.externalJsLinks == undefined) { ProfileApp.externalJsLinks = {} }
var article = $('.profile-item[data-id=2135726] article');
var html = $('<div class=\'product\'>\n<img class=\'cover\' src=\'/uploads/coin_types/2/icon/ThreeDollars.gif\'>\n<div class=\'details\'>\n<h3>Jonny Antimatter<\/h3>\n<span class=\'product-type\'>\n\$ 17.57\ncoin\n<\/span>\n<\/div>\n<\/div>\n');
var groupeesRe = /^http[s]*:\/\/groupees/im;

$.each(html.find('script[src*="http"]'), function(i, item){
  if (groupeesRe.exec(item.src)) {
    return true; //skip internal links
  }
  if (ProfileApp.externalJsLinks[item.src])  {
    $(item).remove()
  } else {
    ProfileApp.externalJsLinks[item.src] = true
  }
});
```

**Comment by GMMan** [comment]
Could you screenshot the bundle for a bit more context? I'm not sure if I've actually encountered giveaway bundles on my account, so this is all a bit new. Also do you have examples of any other giveaway bundles?
